### ISSUE TITLE
Error with get_chanlocs

### ISSUE THREAD

**Issue by natalie-richer** [sccn/get_chanlocs#12]
Hi,

I am running Matlab R2021b, EEGLAB v.2024 and have updated get_chanlocs. When I try to run get_chanlocs, after selecting an OBJ file, I get an error message:

Unrecognized function or variable 'fetch_url'.

Error in ft_read_headshape (line 212)
filename = fetch_url(filename);

Error in get_chanlocs (line 172)
head_surface = ft_read_headshape([objPath, filesep, getfield(dir([objPath filesep '*.obj']),'name')],...

Is fetch_url a newer Matlab function? What can I do to solve the issue? I was using get_chanlocs successfully in the past, but it no longer works.

Thanks,
Natalie

**Comment by neuromechanist** [comment]
Hi Natalie,

Thanks for reporting the issue. It seems that the the fetch_url function is from Fieldtrip. Do you mind checking if you have the latest Fieldtrip on your path?

**Comment by natalie-richer** [comment]
Thank you, Seyed! The specific folder containing fetch_url wasn't on my path - this was very helpful!

**Comment by neuromechanist** [comment]
Awesome, great to hear.
